version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-api-basica
    environment:
      MONGO_INITDB_ROOT_USERNAME: develop
      MONGO_INITDB_ROOT_PASSWORD: Dbabnsmdb2024
      MONGO_INITDB_DATABASE: api_basica_nestjs_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local
